name: chatterpie
description: A chat apps Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.1.1
  firebase_storage: ^3.1.1
  fluttertoast: ^3.1.3

flutter:

  uses-material-design: true

  assets:
  - assets/images/inu.png
  - assets/images/tehtarik.png


